63 - CRUD jogos
CUBA-dev/bgshelfie-backend pull request #4
Opened 2021-01-27 13:13 UTC by tfbbueno

Parte mais simples do crud de jogo. Ainda preciso estudar como fazer  upload de imagens, e outras coisas. Deixei um TODO no model de jogo.

2021-01-29 00:59 UTC, sayuriarake commented
.

2021-02-05 15:11 UTC, tfbbueno commented
@sayuriarake @alinnebarrozo avaliem meu PR, suas lindas

2021-02-06 01:27 UTC, sayuriarake requested changes

2021-02-06 01:27 UTC, sayuriarake commented on cuba.dev/app/controllers/dominio.js
> -              res.status(404).json("Domínio não encontrado") :
Tava com "registro", eu que mudei pra "dominio não encontrado, pq todos os outros já seguiam esse padrão. Meu TOC grita com coisas despadronizadas. Meu receio é que, em caso de pipoco, não vamos saber qual registro de fato não foi encontrado, pq tudo estará "registro não encontrado".

2021-02-06 01:27 UTC, sayuriarake commented on cuba.dev/app/models/jogo.js
> +      quantidadeJogadoresMax: {
required:true

2021-02-06 01:27 UTC, sayuriarake commented on cuba.dev/app/models/jogo.js
> +        required: true,
não sei se todos os jogos essa informação é obrigada. talvez teremos que pesquisar isso.

2021-02-08 15:57 UTC, tfbbueno commented on cuba.dev/app/controllers/dominio.js
> -              res.status(404).json("Domínio não encontrado") :
Já eu, queria seguir o padrão para Registro kkkkkkkkkkkkkkkk


Mas sua linha de pensamento faz sentido, vou refatorar

2021-02-10 23:13 UTC, tfbbueno commented on cuba.dev/app/models/jogo.js
> +      quantidadeJogadoresMax: {
Mas aí eu deixei aberto pensando em RPG. RPG não tem quantidade máxima

2021-02-10 23:13 UTC, tfbbueno commented on cuba.dev/app/models/jogo.js
> +      quantidadeJogadoresMax: {
Ou tem?

2021-02-10 23:14 UTC, tfbbueno commented on cuba.dev/app/models/jogo.js
> +        required: true,
Vou deixar sem required

2021-02-11 01:54 UTC, sayuriarake commented on cuba.dev/app/models/jogo.js
> +      quantidadeJogadoresMax: {
limite máximo de jogadores é a quantidade de entes no universo. ahsuhasuhuashuashusahusahuas
ok, favor desconsiderar

2021-02-11 01:56 UTC, sayuriarake approved these changes

2021-02-15 00:50 UTC, merged